# Generated by Django 5.1.2 on 2024-12-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
