# Generated by Django 5.1.2 on 2024-12-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_telegramuser_is_authenticated'),
    ]

    operations = [
    ]
