# Generated by Django 5.1.2 on 2024-11-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0006_remove_review_order_id_review_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
        migrations.AddField(
            model_name='review',
            name='order_id',
            field=models.IntegerField(default=27),
            preserve_default=False,
        ),
    ]
